# Generated by Django 5.2.4 on 2026-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
