# Generated by Django 5.2.4 on 2026-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='profession',
            field=models.CharField(choices=[('software', 'Software Developer'), ('data', 'Data Analyst'), ('hr', 'HR'), ('accounting', 'Accounting'), ('teaching', 'Teaching'), ('retail', 'Retail'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
