# Generated by Django 6.0.7 on 2026-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
