# Generated by Django 6.0.7 on 2026-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_opportunity_click_count_opportunity_last_clicked_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['is_active'], name='core_opport_is_acti_fc607a_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type'], name='core_opport_opportu_796600_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['application_deadline'], name='core_opport_applica_693453_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['-date_listed'], name='core_opport_date_li_d70e1e_idx'),
        ),
    ]
