# Generated by Django 6.0.7 on 2026-08-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_opportunity_core_opport_is_acti_fc607a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opportunity',
            name='core_opport_applica_693453_idx',
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['is_active', 'opportunity_type'], name='core_opport_is_acti_f0d181_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['is_active', '-date_listed'], name='core_opport_is_acti_712a08_idx'),
        ),
    ]
