# Generated by Django 6.0.7 on 2026-08-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_opportunity_core_opport_applica_693453_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='idx_is_active',
            old_name='core_opport_is_acti_fc607a_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='idx_opportunity_type',
            old_name='core_opport_opportu_796600_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='idx_date_listed',
            old_name='core_opport_date_li_d70e1e_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='idx_active_type',
            old_name='core_opport_is_acti_f0d181_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='idx_active_date',
            old_name='core_opport_is_acti_712a08_idx',
        ),
    ]
