# Generated by Django 5.2.4 on 2026-05-16 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], max_length=20)),
                ('question_count', models.IntegerField(default=5)),
                ('cv_text', models.TextField(blank=True, null=True)),
                ('popia_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('overall_presence_score', models.FloatField(blank=True, null=True)),
                ('eye_contact_score', models.FloatField(blank=True, null=True)),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('gesture_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('structure_score', models.FloatField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('behavioural', 'Behavioural'), ('technical', 'Technical'), ('situational', 'Situational'), ('competency', 'Competency')], default='behavioural', max_length=20)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('eye_contact_score', models.FloatField(blank=True, null=True)),
                ('posture_score', models.FloatField(blank=True, null=True)),
                ('gesture_score', models.FloatField(blank=True, null=True)),
                ('presence_score', models.FloatField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interviews/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='interviews/video/')),
                ('answer_feedback', models.TextField(blank=True, null=True)),
                ('answer_strengths', models.JSONField(blank=True, default=list)),
                ('answer_improvements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interview')),
            ],
            options={
                'ordering': ['question_index'],
            },
        ),
    ]
